tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "awscli"
brew "azure-cli"
brew "direnv"
brew "fish"
brew "go"
brew "hey"
brew "node", link: false
brew "pyenv"
brew "stow"
brew "tmux"
brew "tree"
cask "vscodium"
cask "iterm2"
